### ISSUE TITLE
Issue following https://docs.computes.com/docs/chained-task example

### ISSUE THREAD

**Issue by tyvdh** [computes/help#6]
Everything goes smooth until the last command. Fairly certain I'm following the example to a T.

Only issue is that on the last bit here https://docs.computes.com/docs/chained-task#section-edit-split-taskjson it mentions inputing 3 hashes but on split-task there's only two places to input hashes.

```bash
[GIN] 2018/06/21 - 14:16:20 | 204 |   19.156627ms |             ::1 |  PUT     /v1/tasks/zdpuAoqjvK9zsTX6ZDMAzxcTZLfuFsMTDPbqJcqq46MjMAAfS
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1341522]

goroutine 152 [running]:
github.com/computes/go-computes/vendor/github.com/computes/go-ipld-polymorph.(*Polymorph).IsRef(0x0, 0xc42084acc0)
	vendor/github.com/computes/go-ipld-polymorph/polymorph.go:255 +0x22
github.com/computes/go-computes/vendor/github.com/computes/go-ipld-polymorph.(*Polymorph).CalcRef(0x0, 0xc42084acf0, 0x0, 0x0, 0x0)
	vendor/github.com/computes/go-ipld-polymorph/polymorph.go:101 +0x2f
github.com/computes/go-computes/pkg/workers/runner.(*Runner).RunDockerTask(0xc420174000, 0x19de300, 0xc42012cf80, 0x1, 0x15b8420, 0xc420528e60, 0x1829a22, 0x20)
	pkg/workers/runner/runner.go:81 +0xb4
github.com/computes/go-computes/pkg/workers/runner.(*Runner).RunTask(0xc420174000, 0x19de300, 0xc42012cf80, 0x31, 0xc420832380, 0xc4202a64a0, 0xc420832380, 0x31)
	pkg/workers/runner/runner.go:61 +0x1d5
github.com/computes/go-computes/pkg/workers/runner.(*Runner).doTask(0xc420174000, 0x19de300, 0xc42012cf80, 0x19deb00, 0xc420528e60, 0x0, 0x0)
	pkg/workers/runner/runner.go:183 +0x5a
github.com/computes/go-computes/pkg/workers/runner.(*Runner).Do(0xc420174000, 0x0, 0x0, 0x0)
	pkg/workers/runner/runner.go:172 +0x2b2
github.com/computes/go-computes/pkg/workers.(*Worker).Run(0xc4204cdc20, 0xc4204cdc20, 0xc420372060)
	pkg/workers/worker.go:65 +0xaf
created by github.com/computes/go-computes/pkg/workers.(*Worker).Start
	pkg/workers/worker.go:49 +0x388
```

Any ideas?

**Comment by iamruinous** [comment]
Sorry about that, I forgot to update the examples. They are now correct. The change you need to make is in your task definition, instead of `{"metadata":...` it should now be 
```json
{
  "manifest": {
    "*": {
      "image": "..."
    }
  }
}
```

**Comment by tyvdh** [comment]
So that doesn't result in an error but now I get:

```bash
{"__meta__":{"computes":{"seed":"67b3fe40-4602-4077-adfa-09996fe619a0","tasks":{"related":["zdpuAtwKsHQiV3xRMsiBqq6GzoNP9xKTTtUjoG6EGDhBMiV8y"]}}},"split":{"results":[1,2]}}
```

Which is not what I expected.

There are a few issues still though in the examples.

![screen shot 2018-06-21 at 2 48 42 pm](https://user-images.githubusercontent.com/4383610/41739359-d763f1ac-7562-11e8-9ccf-6ac8ae0bfe95.png)

Header says add split-task-definition when if fact you are adding map-task-definition

![screen shot 2018-06-21 at 2 49 54 pm](https://user-images.githubusercontent.com/4383610/41739388-e8bc6c36-7562-11e8-9764-24a8e2c42d78.png)

Says to add three hashes to split-task.json but https://github.com/computes/help/blob/master/examples/chained-task/split-task.json only has two spaces for hashes.

**Comment by iamruinous** [comment]
Thanks for pointing out those errors in the docs. I've corrected them. 

I see one problem in your task definition:
```json
{
  "conditions": [
    {
      "action": "map",
      "condition": "exist(dataset(hpcp(zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi/split/results'))) && !exist(dataset(hpcp('zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi/map/results')))",
      "name": "Create Map tasks",
      "source": {
        "dataset": {
          "/": "zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi"
        },
        "path": "split/results"
      },
      "taskDefinition": {
        "/": "zdpuAxF89h5yntaTqwhzfjQGT4nYcqsCwBB4E5N4bqevCJsfw"
      }
    }
  ],
  "result": {
    "action": "set",
    "destination": {
      "dataset": {
        "/": "zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi"
      },
      "path": "split/results"
    }
  },
  "runner": {
    "manifest": {
      "*": {
        "image": "computes/fibonacci-sum-split:latest"
      }
    },
    "type": "docker-json-runner"
  }
}
```

The condition is missing a single quote and should be 
```json
"exist(dataset(hpcp('zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi/split/results'))) && !exist(dataset(hpcp('zdpuB2W5sZXoNCXzZUnyAxgoy3VsUCxtrDVQxRHjqYhEJCNpi/map/results')))",
```

**Comment by iamruinous** [comment]
I'll see if we can notify the task somehow that the conditions were invalid when they were evaluated.

**Comment by tyvdh** [comment]
Ah ha! Good catch.

Might be nice to have text that should be drop replaced to be stuff that can be double click replaced.

`<abc-123>` -> `abc_123`

Just a thought.

Thanks again for all the help!
